# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tier < Formula
  desc "The Tier CLI"
  homepage "https://tier.run/"
  version "0.5.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tierrun/tier/releases/download/v0.5.1/tier_0.5.1_macOS_arm64.tar.gz"
      sha256 "40bdd0a8211a317b02c88e8f07eff7d04b6e28807722d5460f6961882d85e1df"

      def install
        bin.install "tier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tierrun/tier/releases/download/v0.5.1/tier_0.5.1_macOS_amd64.tar.gz"
      sha256 "6e13c73701cff9f4ceb4cd5bc37783edfdca1281445561755eed5240e8ceaee6"

      def install
        bin.install "tier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tierrun/tier/releases/download/v0.5.1/tier_0.5.1_linux_arm64.tar.gz"
      sha256 "76e3824a5915b1c59f486a47124112fa68ca1252d3ffc5ba34661f33f9036abd"

      def install
        bin.install "tier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tierrun/tier/releases/download/v0.5.1/tier_0.5.1_linux_amd64.tar.gz"
      sha256 "94e772bad6e426d3711e0a862998331ec3eb4d27875b2aa6052f757c3d2cc8ba"

      def install
        bin.install "tier"
      end
    end
  end

  test do
    system "#{bin}/tier version --homebrew"
  end
end
