# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tier < Formula
  desc "The Tier CLI"
  homepage "https://tier.run/"
  version "0.4.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tierrun/tier/releases/download/v0.4.0/tier_0.4.0_macOS_arm64.tar.gz"
      sha256 "8b94ecf525d906fbee3e8ad92b3aaea4b2b8ebe817bf3b9f04ab3d0440654321"

      def install
        bin.install "tier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tierrun/tier/releases/download/v0.4.0/tier_0.4.0_macOS_amd64.tar.gz"
      sha256 "6a8ade93b6af6f09dc7a09a15db019ec59197d389edea62af51d6e2f6944dea2"

      def install
        bin.install "tier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tierrun/tier/releases/download/v0.4.0/tier_0.4.0_linux_arm64.tar.gz"
      sha256 "729199f28a252acdd8eccd7149b9840e129a5b5b2dff997d119600c353c70712"

      def install
        bin.install "tier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tierrun/tier/releases/download/v0.4.0/tier_0.4.0_linux_amd64.tar.gz"
      sha256 "58350ff188e2d430936e884619dc503121ad7dcb1bb5c6ad3e75127c5a9363ac"

      def install
        bin.install "tier"
      end
    end
  end

  test do
    system "#{bin}/tier version --homebrew"
  end
end
