# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tier < Formula
  desc "The Tier CLI"
  homepage "https://tier.run/"
  version "0.8.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tierrun/tier/releases/download/v0.8.0/tier_0.8.0_darwin_amd64.tar.gz"
      sha256 "eddf0c57e3987a5fd1533789acbb22b10f3e6f4f8a6236b79e483f3cb79cd0dd"

      def install
        bin.install "tier"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tierrun/tier/releases/download/v0.8.0/tier_0.8.0_darwin_arm64.tar.gz"
      sha256 "0fa9bc0d40fec27ea37f18009f4eefe8dba5d736c9a541508e19bda46b265505"

      def install
        bin.install "tier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tierrun/tier/releases/download/v0.8.0/tier_0.8.0_linux_arm64.tar.gz"
      sha256 "c2e634599deeedd02efb70e695d75bb16c0aacec9eb8a1cfa41d13146a48bfd7"

      def install
        bin.install "tier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tierrun/tier/releases/download/v0.8.0/tier_0.8.0_linux_amd64.tar.gz"
      sha256 "f3846d501653e21bfb7164ca9d25e8d25ab10c529d10368d8df1002efdae24fa"

      def install
        bin.install "tier"
      end
    end
  end

  test do
    system "#{bin}/tier version --homebrew"
  end
end
